### ISSUE TITLE
Randomizer

### ISSUE THREAD

**Issue by binocarlos** [strange-labs-uk/ethereum-raffle#1]
An issue to capture what we were saying last night:

 * the lottery will be a raffle - with guaranteed winners each week / time period
 * we need sources of entropy but ideally would not use an external oracle - possible sources of entropy:
    * all wallet addresses that have played that week
    * hash of all previous wallet addresses that have ever played
    * block number & hash at the moment the winners are decided
    * perhaps we allow folks to enter random text as an anti-cheat feature
 * we condense these sources of entropy
 * gas cost should be ok because we should be sat on some cash by this point
 * the amount of gas needed will be relative to how many folks have played
 * the more folks who have played - the more the gas will cost but also the more funds we will have to pay the gas
 * hash the condensed sources of entropy to get a single SHA256 string - call this RANDOM_STRING
 * we have a list of wallet addresses in an indexed list - in time order of when they submitted their payment - the length of this list is N
 * take a slice of the RANDOM_STRING and turn it into a large number - call this RANDOM_NUMBER
 * do a modulus to get the index of the winning ticket (RANDOM_NUMBER % N)

Things to work out:

 * exactly how we turn (RANDOM_NUMBER % N) into an index for the winning ticket (I can see it works but not exactly how we map onto a bounded index)
 * how we condense the sources of entropy
 * if the gas cost theory actually works

**Comment by TikiMeat** [comment]
I haven't had a change to fully digest it yet but there's a few people discussing the issue here: https://ethereum.stackexchange.com/questions/191/how-can-i-securely-generate-a-random-number-in-my-smart-contract

**Comment by px3l** [comment]
https://bitcoin.stackexchange.com/questions/53/is-there-a-way-to-use-the-block-chain-as-entropy-in-random-number-generator

**Comment by px3l** [comment]
Ok, so maybe the following:

Each token buyer generates a random number off chain, locally. This number is hashed with their address and the result is pushed to a contract. The local "random number" means it doesn't matter if it is "not random"(?) ie not truly mathematically random, because it is hashed and used to decode finally.

**Comment by brtknr** [comment]
I think we pretty much solved this as best as we could!
