### ISSUE TITLE
Create mechanism whereby the draw doesn't start until it has at least x players

### ISSUE THREAD

**Issue by px3l** [strange-labs-uk/ethereum-raffle#18]
To avoid:
1. Losing money deploying useless contracts
2. The (amusing) scenario where there is 1 player or something who will lose 10% of their money but be the guaranteed winner

**Comment by brtknr** [comment]
maybe greater than 1? then at least you end up with more than where you started?

**Comment by binocarlos** [comment]
So it sounds like we need to:

 * have a parameter of a game called `minPlayers`
 * merge the `startGame` and `endGame` absolute timestamps into a `gamePeriod` single, relative timestamp

Then - on each call to `play` - it says `are there enough players now` - if yes and game has not started - set `gameStarted` to current block timestamp and `gameWillEnd` to `gameStarted + gamePeriod`

We probably need another var called `gameActive` so the various `require` statements in `canPlayGame` still work with regard to the game being active but the time period not technically started.

**Comment by brtknr** [comment]
Ofcourse, player at index minPlayer will need to pay for a couple of lines of extra computational cost!

**Comment by binocarlos** [comment]
New proposal - have a `minPlayers` variable as part of the contract - if the `endTime`  comes and there are `< X` players - trigger the refundAll function
