### ISSUE TITLE
what happens if: if(numPlayers > 0) is 0?

### ISSUE THREAD

**Issue by px3l** [strange-labs-uk/ethereum-raffle#19]
black hole?

**Comment by brtknr** [comment]
Please clarify

**Comment by binocarlos** [comment]
This can be closed - the worry was that in the `draw` function - the following codepath:
```
if(numTickets > 0) {
 // do the draw...
}
```
Meant that if zero tickets were sold - the game went into a **black hole** and a new game could not be started...

However - before the `if(numTickets > 0) {` there is: `settings.complete = block.timestamp;` which means even though no draw actually takes place - the game is complete and so the next game can be created.  This is what we would want to happen and so the answer to @px3l 's question is:

> what we want to happen

- which is good :)

Closing...
